version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - VITE_WEBHOOK_URL=${VITE_WEBHOOK_URL}
      - VITE_WEBHOOK_AUTH_HEADER=${VITE_WEBHOOK_AUTH_HEADER}
      - VITE_WEBHOOK_AUTH_TOKEN=${VITE_WEBHOOK_AUTH_TOKEN}
      - VITE_SPEECH_RECOGNITION_LANGUAGE=${VITE_SPEECH_RECOGNITION_LANGUAGE}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3